### ISSUE TITLE
Startup crash: socket directory missing

### ISSUE THREAD

**Issue by carsonoid** [EugenMayer/docker-image-portus#10]
Getting this when trying to start the container. 

I was able to fix it by adding `mkdir -p /portus/tmp/sockets` into the startup script before starting puma.

```
/usr/local/bundle/gems/puma-3.7.0/lib/puma/binder.rb:366:in `initialize': No such file or directory - connect(2) for /portus/tmp/sockets/puma.sock (Errno::ENOENT)
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/binder.rb:366:in `new'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/binder.rb:366:in `add_unix_listener'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/binder.rb:141:in `block in parse'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/binder.rb:88:in `each'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/binder.rb:88:in `parse'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/runner.rb:144:in `load_and_bind'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/cluster.rb:391:in `run'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/launcher.rb:171:in `run'
	from /usr/local/bundle/gems/puma-3.7.0/lib/puma/cli.rb:77:in `run'
	from /usr/local/bundle/gems/puma-3.7.0/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:17:in `load'
	from /usr/local/bundle/bin/puma:17:in `<main>'
```

**Comment by EugenMayer** [comment]
Never ran into this yet. Did you build your own version, that said, your own image based on a e.g. more recent portus version?

**Comment by carsonoid** [comment]
Just using the latest code from master. I think the ENV variables have changed upstream, Ex: PORTUS_HOST has become PORTUS_PUMA_HOST

So Portus isn't noticing my desired listen host/port and trying to use a socket.

**Comment by EugenMayer** [comment]
Did you find any changelog or notice about that? So we can work on those items as a whole

**Comment by carsonoid** [comment]
Offending commit here: https://github.com/SUSE/Portus/commit/9fd61ba7bae0f8343961adb99000527d7a1d23fc

Maybe the build should be based off a specific release tag instead of master? That would make things more stable.

**Comment by EugenMayer** [comment]
well actually this build is made to build the most recent one, but the docker image releases are version on "stable" ones. So i woudl rather keep it. Thanks for the commit, thats interesting!

**Comment by EugenMayer** [comment]
Are you specificly talking about `PORTUS_PRODUCTION_HOST` and `PORTUS_DEVELOPMENT_HOST` ? There is no PORTUS host, neither in the startup.sh nor in the docker-compose so i have no idea what your are referencing to.

**Comment by EugenMayer** [comment]
http://port.us.org/docs/upgrading-portus.html

**Comment by zaggash** [comment]
I had the same issue here

**Comment by kuhnroyal** [comment]
Same problem here
